#!/usr/bin/env bash

set -eu

SUPPORT_DIR="${BASH_SOURCE[0]%/*}/../../support"
VENDOR_DIR="${SUPPORT_DIR}/vendor"

PATH="${VENDOR_DIR}/ktlint:$PATH"

git diff --name-only --cached --relative | grep '\.kt[s"]\?$' | xargs ktlint --android --relative .
if [ $? -ne 0 ]; then exit 1; fi
