#!/usr/bin/env bash
# Writes ios/Config/Telemetry.local.xcconfig, the gitignored file that gives the S2 target its Sentry DSN and PostHog
# key and host (#776). Each value comes from the environment (SENTRY_DSN, POSTHOG_API_KEY, POSTHOG_HOST), else from
# ~/.config/s2-telemetry/ios.env (the same names, one KEY=value per line; S2_TELEMETRY_ENV picks another file).
# A key found in neither stays empty, and that SDK stays off: the build never needs them.
#
# Never prints a value, only whether each key is set. build-framework.sh runs it; it rewrites the file only when its
# contents change, so an unchanged key never invalidates the build.
set -euo pipefail

repo_root="$(cd "$(dirname "$0")/../.." && pwd)"
out="$repo_root/ios/Config/Telemetry.local.xcconfig"
env_file="${S2_TELEMETRY_ENV:-$HOME/.config/s2-telemetry/ios.env}"

# The env file is parsed, never sourced: only these three names are read, and nothing in it runs.
from_file() {
  [[ -r "$env_file" ]] || return 0
  local line
  line="$(grep -E "^[[:space:]]*(export[[:space:]]+)?$1=" "$env_file" | tail -n 1)" || return 0
  line="${line#*=}"
  line="${line%$'\r'}"
  line="${line#\"}"; line="${line%\"}"
  line="${line#\'}"; line="${line%\'}"
  printf '%s' "$line"
}

value() {
  local name="$1"
  if [[ -n "${!name:-}" ]]; then printf '%s' "${!name}"; else from_file "$name"; fi
}

# In an xcconfig, `//` starts a comment, so a URL's is written `/$()/` (an empty expansion between the slashes)
xcconfig_escape() {
  printf '%s' "$1" | sed 's#//#/$()/#g'
}

sentry_dsn="$(value SENTRY_DSN)"
posthog_key="$(value POSTHOG_API_KEY)"
posthog_host="$(value POSTHOG_HOST)"

contents="// Generated by ios/scripts/generate-telemetry-config.sh. Gitignored: never commit it.
S2_SENTRY_DSN = $(xcconfig_escape "$sentry_dsn")
S2_POSTHOG_API_KEY = $(xcconfig_escape "$posthog_key")"
# An empty host keeps Telemetry.xcconfig's default, PostHog's EU cloud
if [[ -n "$posthog_host" ]]; then
  contents+="
S2_POSTHOG_HOST = $(xcconfig_escape "$posthog_host")"
fi
contents+=$'\n'

if [[ ! -f "$out" ]] || [[ "$(cat "$out")"$'\n' != "$contents" ]]; then
  umask 077
  printf '%s' "$contents" > "$out"
fi

state() { if [[ -n "$1" ]]; then echo set; else echo "not set, off"; fi; }
echo "==> telemetry keys: Sentry DSN $(state "$sentry_dsn"), PostHog key $(state "$posthog_key")"
