#!/usr/bin/env python3
"""Writes ios/S2/en.lproj/Localizable.strings: the English text of every StringKey, from Android's strings.xml.

StringKey (android/presentation, ui/text/StringKey.kt) names the strings shared code shows; each entry's lower-case
name is both the Android resource name and the iOS Localizable key, so the text has one source. Run it after
adding a StringKey or changing its English text:

    ios/scripts/generate-strings.py            # rewrite the file
    ios/scripts/generate-strings.py --check    # exit 1 if the file is stale (nothing written)

Android's `%1$s` becomes `%1$@` (UiText passes every non-count argument as a string); `%d` stays. PluralKeys
(`.stringsdict`) and translations aren't generated yet.
"""

import re
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
STRING_KEY = ROOT / "android/presentation/src/commonMain/kotlin/com/simplecityapps/shuttle/ui/text/StringKey.kt"
OUTPUT = ROOT / "ios/S2/en.lproj/Localizable.strings"


def string_keys():
    source = STRING_KEY.read_text()
    body = source[source.index("enum class StringKey"):]
    body = body[body.index("{") + 1:body.index("}")]
    body = re.sub(r"/\*.*?\*/", "", body, flags=re.S)
    body = re.sub(r"//[^\n]*", "", body).split(";")[0]
    return [name.strip().lower() for name in body.split(",") if name.strip()]


def android_strings():
    strings = {}
    for path in sorted(ROOT.glob("android/**/src/*/res/values/*.xml")):
        if "/build/" in str(path):
            continue
        for element in ET.parse(path).getroot().iter("string"):
            text = "".join(element.itertext())
            strings[element.get("name")] = text
    return strings


def ios_text(android):
    text = android.strip()
    if len(text) >= 2 and text[0] == '"' and text[-1] == '"':
        text = text[1:-1]
    text = text.replace("\\'", "'").replace('\\"', '"').replace("\\n", "\n")
    text = re.sub(r"%(\d+\$)?s", lambda m: f"%{m.group(1) or ''}@", text)
    return text.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")


def render():
    strings = android_strings()
    lines = [
        "/* Generated by ios/scripts/generate-strings.py from Android's strings.xml: the English text of every",
        "   StringKey. Don't edit; change the Android string and run the script. */",
        "",
    ]
    missing = []
    for key in string_keys():
        if key not in strings:
            missing.append(key)
            continue
        lines.append(f'"{key}" = "{ios_text(strings[key])}";')
    if missing:
        sys.exit(f"No Android string for StringKey entries: {', '.join(missing)}")
    return "\n".join(lines) + "\n"


def main():
    content = render()
    if "--check" in sys.argv[1:]:
        if not OUTPUT.exists() or OUTPUT.read_text() != content:
            sys.exit(f"{OUTPUT.relative_to(ROOT)} is stale: run ios/scripts/generate-strings.py")
        return
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(content)
    print(f"Wrote {OUTPUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
