#!/usr/bin/env bash
# Writes ios/Config/LastFm.local.xcconfig, the gitignored file that gives the S2 target its Last.fm API key and shared
# secret (#503). Each value comes from the environment (LASTFM_API_KEY, LASTFM_SHARED_SECRET), else from the repo's
# local.properties, else from the Gradle user home's gradle.properties (both where the Android build reads the same
# names), else from ~/.config/s2-lastfm/ios.env (the same names, one KEY=value per line; S2_LASTFM_ENV picks another
# file). A worktree without a local.properties of its own reads the primary checkout's. Without both values scrobbling is off and its Settings row hidden: the build never
# needs them.
#
# Never prints a value, only whether the keys are set. build-framework.sh runs it; it rewrites the file only when its
# contents change, so an unchanged key never invalidates the build.
set -euo pipefail

repo_root="$(cd "$(dirname "$0")/../.." && pwd)"
out="$repo_root/ios/Config/LastFm.local.xcconfig"
env_file="${S2_LASTFM_ENV:-$HOME/.config/s2-lastfm/ios.env}"
gradle_properties="${GRADLE_USER_HOME:-$HOME/.gradle}/gradle.properties"

local_properties="$repo_root/local.properties"
if [[ ! -r "$local_properties" ]]; then
  common_dir="$(git -C "$repo_root" rev-parse --path-format=absolute --git-common-dir 2>/dev/null || true)"
  [[ -n "$common_dir" ]] && local_properties="$(dirname "$common_dir")/local.properties"
fi

# The files are parsed, never sourced: only the two names are read, and nothing in them runs.
from_file() {
  local file="$1" name="$2" line
  [[ -r "$file" ]] || return 0
  line="$(grep -E "^[[:space:]]*(export[[:space:]]+)?$name[[:space:]]*=" "$file" | tail -n 1)" || return 0
  line="${line#*=}"
  line="${line%$'\r'}"
  line="$(printf '%s' "$line" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')"
  line="${line#\"}"; line="${line%\"}"
  line="${line#\'}"; line="${line%\'}"
  printf '%s' "$line"
}

value() {
  local name="$1" found
  if [[ -n "${!name:-}" ]]; then printf '%s' "${!name}"; return; fi
  found="$(from_file "$local_properties" "$name")"
  if [[ -n "$found" ]]; then printf '%s' "$found"; return; fi
  found="$(from_file "$gradle_properties" "$name")"
  if [[ -n "$found" ]]; then printf '%s' "$found"; return; fi
  from_file "$env_file" "$name"
}

api_key="$(value LASTFM_API_KEY)"
shared_secret="$(value LASTFM_SHARED_SECRET)"

contents="// Generated by ios/scripts/generate-lastfm-config.sh. Gitignored: never commit it.
S2_LASTFM_API_KEY = $api_key
S2_LASTFM_SHARED_SECRET = $shared_secret
"

if [[ ! -f "$out" ]] || [[ "$(cat "$out")"$'\n' != "$contents" ]]; then
  umask 077
  printf '%s' "$contents" > "$out"
fi

if [[ -n "$api_key" && -n "$shared_secret" ]]; then
  echo "==> Last.fm keys: set"
else
  echo "==> Last.fm keys: not set, scrobbling off"
fi
