package com.simplecityapps.shuttle.smartplaylist

import com.simplecityapps.shuttle.model.MediaProviderType
import com.simplecityapps.shuttle.model.Song
import kotlin.time.Instant
import kotlinx.datetime.LocalDate

internal fun song(
    id: Long = 1,
    name: String? = "Song",
    albumArtist: String? = "Album Artist",
    artists: List<String> = listOf("Artist"),
    album: String? = "Album",
    track: Int? = 1,
    disc: Int? = 1,
    duration: Int = 180_000,
    date: LocalDate? = null,
    genres: List<String> = emptyList(),
    path: String = "/music/song.mp3",
    mimeType: String = "audio/mpeg",
    lastModified: Instant? = null,
    lastPlayed: Instant? = null,
    lastCompleted: Instant? = null,
    playCount: Int = 0,
    mediaProvider: MediaProviderType = MediaProviderType.Shuttle,
    grouping: String? = null,
    bitRate: Int? = null,
    bitDepth: Int? = null,
    sampleRate: Int? = null,
    dateAdded: Instant? = null,
) = Song(
    id = id,
    name = name,
    albumArtist = albumArtist,
    artists = artists,
    album = album,
    track = track,
    disc = disc,
    duration = duration,
    date = date,
    genres = genres,
    path = path,
    size = 0,
    mimeType = mimeType,
    lastModified = lastModified,
    lastPlayed = lastPlayed,
    lastCompleted = lastCompleted,
    playCount = playCount,
    playbackPosition = 0,
    blacklisted = false,
    mediaProvider = mediaProvider,
    lyrics = null,
    grouping = grouping,
    bitRate = bitRate,
    bitDepth = bitDepth,
    sampleRate = sampleRate,
    channelCount = null,
    dateAdded = dateAdded,
)
