#!/usr/bin/env bash

set -xeu
set -o pipefail

# Overridable Environment
BUILD_PATH=${BUILD_PATH:-build}
CONFIGURATION=${CONFIGURATION:-Debug}
RESULT_PATH=${RESULT_PATH:-${BUILD_PATH}/Artifacts}

# Other variables
# eg: JUNIT_PATH="${RESULT_PATH}/test-results.xml"
#SUPPORT_DIR="${BASH_SOURCE[0]%/*}/.."


function finish() {
  # Do any work necessary even if script this fails
  echo "Finished"
}

trap finish EXIT

# Perform Unit Tests
./gradlew :android:app:test
