pipeline {
    agent any

    stages {
        stage('Test') {
            steps {
                withCredentials(
                        [
                                file(credentialsId: 'b56a70ed-91fe-463c-a5c1-9ceecd55f4c5', variable: 'DEPLOYMENT_KEYS'),
                                file(credentialsId: 'f2bd02bf-a6c2-45a3-8b57-b44b5247866f', variable: 'GOOGLE_SERVICES'),
                                string(credentialsId: 'db8e0f78-0061-4c94-a1c2-f9efb1ccbe14', variable: 'KEYSTORE_PASS')
                        ]
                ) {
                      sh '.jenkins/test.sh'
                }
            }
        }

        stage('Deploy') {
              when {
                  anyOf {
                        branch 'alpha'
                        branch 'beta'
                        branch 'prod'
                  }
              }
              steps {
                  withCredentials(
                        [
                            file(credentialsId: 'b56a70ed-91fe-463c-a5c1-9ceecd55f4c5', variable: 'DEPLOYMENT_KEYS'),
                            file(credentialsId: 'f2bd02bf-a6c2-45a3-8b57-b44b5247866f', variable: 'GOOGLE_SERVICES'),
                            string(credentialsId: 'db8e0f78-0061-4c94-a1c2-f9efb1ccbe14', variable: 'KEYSTORE_PASS')
                        ]
                  ) {
                         sh '.jenkins/deploy.sh'
                  }
              }
        }

        stage('Notify-Alpha') {
            when {
                branch 'alpha'
            }
            steps {
                sh ".jenkins/notify.sh https://discord.com/api/webhooks/878937338170986506/sPBcdUFAM3Iy9YIBSYdDSGqtrBG9xG-AHeMK9Y73q-rYtYS1d37GbGxZeK06NPMplT9M"
            }
        }

        stage('Notify-General') {
            when {
                anyOf {
                    branch 'beta'
                    branch 'prod'
                }
            }
            steps {
                sh ".jenkins/notify.sh https://discord.com/api/webhooks/655771580839886848/YLD4-9qZPx9Dgd5fap42QQ9R_pyUBpTV0K4gVpFbFAQGUJH-SKbCfhTZvhPMFlSWGss9"
            }
        }
    }
}