package com.simplecityapps.shuttle.baselineprofile

import android.os.ParcelFileDescriptor
import androidx.test.platform.app.InstrumentationRegistry
import androidx.test.uiautomator.UiDevice

/** The release app's id: the benchmark build types keep release's, with no `.dev` suffix. */
const val TARGET_PACKAGE = "com.simplecityapps.shuttle"

/**
 * Gives the app a library before its first launch: copies the sample library the test APK carries (generated by
 * `generateSampleLibrary`) to the device's Music folder, has MediaStore index each file, and grants the music
 * permission, so the app's first launch scans it (`MediaSources.scanIfNeverScanned`) without asking.
 */
object SampleLibrary {
    private const val ASSETS = "sample-library"
    private const val DEVICE_DIR = "/sdcard/Music/s2-profile"
    private const val SEEDED_MARKER = "$DEVICE_DIR/.seeded"

    fun seed() {
        val instrumentation = InstrumentationRegistry.getInstrumentation()
        val device = UiDevice.getInstance(instrumentation)
        device.executeShellCommand("pm grant $TARGET_PACKAGE android.permission.READ_MEDIA_AUDIO")
        device.executeShellCommand("pm grant $TARGET_PACKAGE android.permission.POST_NOTIFICATIONS")
        if (device.executeShellCommand("ls $SEEDED_MARKER").trim() == SEEDED_MARKER) return

        device.executeShellCommand("mkdir -p $DEVICE_DIR")
        val assets = instrumentation.context.assets
        // Playlists last: MediaStore drops a playlist entry whose song it hasn't indexed yet (seed-test-media.sh, #399)
        val files = assets.list(ASSETS).orEmpty().sortedBy { it.endsWith(".m3u") }
        for (name in files) {
            // The shell splits commands on spaces, so the playlists lose theirs
            val path = "$DEVICE_DIR/${name.replace(' ', '_')}"
            val (stdout, stdin) = instrumentation.uiAutomation.executeShellCommandRw("dd of=$path")
            ParcelFileDescriptor.AutoCloseOutputStream(stdin).use { out -> assets.open("$ASSETS/$name").use { it.copyTo(out) } }
            ParcelFileDescriptor.AutoCloseInputStream(stdout).use { it.readBytes() }
            device.executeShellCommand("content call --uri content://media/ --method scan_file --arg $path")
        }
        device.executeShellCommand("touch $SEEDED_MARKER")
    }
}
