import org.jetbrains.kotlin.gradle.dsl.JvmTarget

plugins {
    id 'com.android.library'
    id 'dev.zacsweers.metro'
}

android {
    compileSdk = 37

    defaultConfig {
        minSdkVersion 24
        targetSdkVersion 36

        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
        consumerProguardFiles "consumer-rules.pro"
    }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
    namespace = 'com.simplecityapps.trial'

    buildFeatures.buildConfig = true
}

kotlin {
    compilerOptions {
        jvmTarget = JvmTarget.JVM_17
        optIn.add('kotlin.time.ExperimentalTime')
    }
}

dependencies {

    implementation libs.kotlin.stdlib
    implementation libs.androidx.core.ktx
    implementation libs.androidx.appcompat
    implementation libs.google.material

    // Billing
    implementation libs.billingclient.billingKtx

    // Timber
    implementation libs.timber


    // Coroutines
    api(libs.kotlinx.coroutinesCore)

    implementation project(':android:core')
    implementation project(':android:domain')

    testImplementation libs.junit
    testImplementation libs.mockk
    testImplementation(libs.kotlinx.coroutinesTest)
}